export const specializations = [
  'Cuts and Fades',
  'Cut and Shampoos',
  'Custom Designs',
  'Hair Dying/Coloring',
  'Permanent Coloring',
  'Semi Coloring',
  'Specialty Coloring',
  'Gray Blending',
  'Highlights',
  'Mini',
  'Partial',
  'Full',
  'Cap',
  'Formal Styling/Special Occasions Hair',
  'Perms/Relaxers/Retexturizing',
  'Mens Hair',
  'Womens Hair',
  'Kids Hair',
  'Straight-Razor Shave',
  'Beard & Mustache Trimming and Styling',
  'Eyebrow Styling, Trimming, Waxing',
  'Facial Waxing'
];
